### ISSUE TITLE
Docker v0.9.1 is broken.

### ISSUE THREAD

**Issue by alsimms** [sasha0552/pascal-pkgs-ci#39]
```
Docker compose 
services:
  vllm-server:
    container_name: VLLM
    image: ghcr.io/sasha0552/vllm:v0.9.1 
    runtime: nvidia
    ports:
      - 8000:8000
    volumes:
      - /home/xx/Docker/vllm/models/:/models
      - /dev/shm:/dev/shm
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1,2"]
              capabilities: [gpu]
    environment:
      HUGGING_FACE_HUB_TOKEN: hf_blablabla
      NCCL_DEBUG: INFO
    command: [
      "--host","0.0.0.0",
      "--max-model-len","8192",
      "--gpu-memory-utilization","0.85",
      "--max_num_seqs","512",
      "--model","/models/Qwen2.5-14B-Instruct-Q4_K_M.gguf",
      "--dtype","half",
      "--tensor-parallel-size","2"

######### ERRORS

docker compose up
[+] Running 1/1
 ✔ Container VLLM  Recreated                                                                                                                                                                                                                                             0.3s 
Attaching to VLLM
VLLM  | INFO 08-17 22:33:19 [__init__.py:244] Automatically detected platform cuda.
VLLM  | Traceback (most recent call last):
VLLM  |   File "<frozen runpy>", line 189, in _run_module_as_main
VLLM  |   File "<frozen runpy>", line 112, in _get_module_details
VLLM  |   File "/usr/local/lib/python3.12/dist-packages/vllm/__init__.py", line 13, in <module>
VLLM  |     from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
VLLM  |   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/arg_utils.py", line 22, in <module>
VLLM  |     from vllm.config import (BlockSize, CacheConfig, CacheDType, CompilationConfig,
VLLM  |   File "/usr/local/lib/python3.12/dist-packages/vllm/config.py", line 43, in <module>
VLLM  |     from vllm.transformers_utils.config import (
VLLM  |   File "/usr/local/lib/python3.12/dist-packages/vllm/transformers_utils/config.py", line 33, in <module>
VLLM  |     from vllm.transformers_utils.configs import (ChatGLMConfig, Cohere2Config,
VLLM  |   File "/usr/local/lib/python3.12/dist-packages/vllm/transformers_utils/configs/__init__.py", line 28, in <module>
VLLM  |     from vllm.transformers_utils.configs.ovis import OvisConfig
VLLM  |   File "/usr/local/lib/python3.12/dist-packages/vllm/transformers_utils/configs/ovis.py", line 76, in <module>
VLLM  |     AutoConfig.register("aimv2", AIMv2Config)
VLLM  |   File "/usr/local/lib/python3.12/dist-packages/transformers/models/auto/configuration_auto.py", line 1312, in register
VLLM  |     CONFIG_MAPPING.register(model_type, config, exist_ok=exist_ok)
VLLM  |   File "/usr/local/lib/python3.12/dist-packages/transformers/models/auto/configuration_auto.py", line 999, in register
VLLM  |     raise ValueError(f"'{key}' is already used by a Transformers config, pick another name.")
VLLM  | ValueError: 'aimv2' is already used by a Transformers config, pick another name.
VLLM exited with code 1

```

**Comment by Leo-Adrian-Code** [comment]
So am I

**Comment by sasha0552** [comment]
these both issues (#38, #39) related to vllm-project/vllm-ascend#2046, I fix them later.

**Comment by alsimms** [comment]
> It looks like this isn’t a core vLLM bug but a config/name conflict:
> 
> ```
> model already used by a transformers config, pick another name
> ```
> 
> That usually happens when the same model identifier is being reused both in the HuggingFace transformers config and in vLLM’s internal registry. Docker then fails to start because the model name is already reserved.
> 
> Fix/workaround:
> 
>     * Rename the model in your compose config to something unique (not colliding with HuggingFace’s default registry names).
> 
>     * Double-check that `HF_HOME`, `TRANSFORMERS_CACHE`, or bind-mounted paths aren’t re-using the same name across multiple services.
> 
>     * Restart with a clean cache (`rm -rf ~/.cache/huggingface` or Docker volume prune) if the collision persists.
> 
> 
> This isn’t tied to state-drift issues we’ve catalogued — it’s more of a naming collision. If you’d like, I can share a quick checklist we built for diagnosing these “silent config conflicts” (covers model naming, registry collisions, and cache isolation). Let me know.

Negative, it has nothing to do with model name. If you look at the docker compose, that's is not the model being used. This is an issue related to HF. If you grab v0.9.0 and create a docker file to upgrade and use HF latest libraries in order to use latest models you will run into this exact same issue.

**Comment by alsimms** [comment]
> these both issues ([#38](https://github.com/sasha0552/pascal-pkgs-ci/issues/38), [#39](https://github.com/sasha0552/pascal-pkgs-ci/issues/39)) related to [vllm-project/vllm-ascend#2046](https://github.com/vllm-project/vllm-ascend/issues/2046), I fix them later.

Thank you.

**Comment by DongyuAI** [comment]
Bypass via fro short use: E:\>docker create --name temp_container ghcr.io/sasha0552/vllm:v0.9.1
f7a8881b61fd73ef41a55765e7f7faa7b0f6c6a6bd3c620d146b0a0170f836ec

E:\>docker cp temp_container:/usr/local/lib/python3.12/dist-packages/vllm/transformers_utils/configs/ovis.py E:/ovis_original.py
Successfully copied 9.73kB to E:\ovis_original.py

E:\>docker rm temp_container
temp_container

**Comment by alsimms** [comment]
> Bypass via fro short use: E:>docker create --name temp_container ghcr.io/sasha0552/vllm:v0.9.1 f7a8881b61fd73ef41a55765e7f7faa7b0f6c6a6bd3c620d146b0a0170f836ec
> 
> E:>docker cp temp_container:/usr/local/lib/python3.12/dist-packages/vllm/transformers_utils/configs/ovis.py E:/ovis_original.py Successfully copied 9.73kB to E:\ovis_original.py
> 
> E:>docker rm temp_container temp_container

@DongyuAI 

Thanks a million, That worked a treat. Running v0.9.1 now and I am enjoying Qwen3.  I modified and mounted the file. Works like a charm. 

Thank you....

Once it gets fixed on container I will re-pull
